# Generated by Django 4.2.11 on 2025-01-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('image1', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cookbook.category')),
                ('liked', models.ManyToManyField(blank=True, null=True, related_name='liked_item', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, null=True, related_name='saved_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
