# Generated by Django 4.2.11 on 2025-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_category_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', to='cookbook.category'),
        ),
    ]
