# Generated by Django 4.2.11 on 2025-01-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_rename_image1_recipe_image_remove_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
    ]
