# Generated by Django 4.2.11 on 2025-01-05 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_remove_recipe_description_remove_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=10000)),
                ('link', models.URLField(max_length=10000)),
                ('categories', models.ManyToManyField(related_name='cards', to='cookbook.category')),
                ('liked', models.ManyToManyField(blank=True, null=True, related_name='liked_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
