# Generated by Django 4.2.11 on 2025-01-06 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_card_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
