# Generated by Django 4.2.11 on 2025-01-08 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_alter_card_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='filename',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
