# Generated by Django 4.2.11 on 2025-01-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_card_filename_card_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
    ]
