# Generated by Django 4.2.11 on 2025-02-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_remove_card_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='session_likes',
            field=models.ManyToManyField(blank=True, related_name='session_likes', to='cookbook.sessionlike'),
        ),
    ]
