# Generated by Django 4.2.11 on 2025-02-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_remove_card_like_count_remove_card_session_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40)),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_votes', to='cookbook.card')),
            ],
        ),
    ]
