# Generated by Django 4.2.11 on 2025-02-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_delete_guestvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_likes', to='cookbook.card')),
            ],
        ),
    ]
