# Generated by Django 4.2.11 on 2025-02-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_anonymouslike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousLike',
        ),
    ]
