# Generated by Django 4.2.11 on 2025-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_delete_anonymouslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='anon_like',
            field=models.IntegerField(default=0),
        ),
    ]
