# Generated by Django 4.2.11 on 2025-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_card_anon_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='categoryname_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='categoryname_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='categoryname_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
